add delete messages in exchange + compatibility with publish message
allan-simon/mock-amqp-server pull request #1
Opened 2018-11-22 13:05 UTC by jaymoulin

2018-11-22 13:09 UTC, allan-simon requested changes

2018-11-22 13:09 UTC, allan-simon commented on service/state.py
> +        exchange['messages'] = deque()
a tiens j'ai pas mis une deque dans l'init  du champ messages

2018-11-22 13:09 UTC, allan-simon commented on service/state.py
> +        exchange = self._queues.get(exchange_name, None)
(meme faute que moi)

2018-11-22 13:11 UTC, jaymoulin commented on service/state.py
> +        exchange = self._queues.get(exchange_name, None)
Yep j'ai pensé a tort que tu creeais une queue qui avait le nom de l'exchange

2018-11-23 13:13 UTC, allan-simon approved these changes

2018-11-23 13:13 UTC, merged